---
- name: Setup Gitlab Server
  hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - vars/main.yml 
  tasks:
    - name: check LANG setting after update
      include_tasks: tasks/locale_settings.yml
      
    - name: Install Gitlab
      include_tasks: tasks/gitlab.yml



  handlers:
    - name: Restart Gitlab
      command: gitlab-ctl reconfigure
      register: gitlab_restart
      listen: restart_gitlab
      failed_when: gitlab_restart_handler_failed_when | bool
    

