---
- hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Download Long Term Jenkins release
    get_url:
      url: https://pkg.jenkins.io/debian-stable/
      dest: /etc/apt/sources.list.d/jenkins.list

  - name: Import jenkins key from url
    ansible.builtin.apt_key:
      state: present
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key

  - name: apt update
    apt:
      name: '*'
      state: latest

  - name: Install java
    apt:
      name: java-11-openjdk-devel
      state: present

  - name: Install jenkins
    apt:
      name: jenkins
      state: latest

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started
