---
- hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  
  - name: Import jenkins key from url
    apt_key:
      state: present
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      
  - apt_repository:
      repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
      state: present
      filename: jenkins
      
  - name: APT Update
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: Install java
    apt:
      name: openjdk-11-jre
      state: present
      update_cache: yes

  - name: Install jenkins
    apt:
      name: jenkins
      state: latest
      update_cache: yes

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started
  - name: Print the jenkins initial Admin Password
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: initialAdminPassword_output
    args:
      executable: /bin/bash
  - debug: 
            var: initialAdminPassword_output.stdout_lines
    
